### PR TITLE
fix: update npm start/build scripts

### PR DESCRIPTION
**Pull request by tomkuk**

### CODE REVIEW

**Comment by zaiste** [comment]
@tomkuk the problem is with the new version of `parallelshell`

**Comment by tomkuk** [comment]
@zaiste which `parallelshell` version is save to use ?

**Comment by tomkuk** [comment]
@zaiste do we really need `parallelshell` ?

**Comment by zaiste** [comment]
@tomkuk OK, so let's remove it from `devDependencies`

**Pull request merged**
